// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageLoginRequest.proto

package com.aime.game.netty.common.protobuf;

public final class MessageLoginRequestProtos {
  private MessageLoginRequestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageLoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aime.game.protobuf.protocol.MessageLoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string login = 1;</code>
     */
    java.lang.String getLogin();
    /**
     * <code>string login = 1;</code>
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>string hash_password = 2;</code>
     */
    java.lang.String getHashPassword();
    /**
     * <code>string hash_password = 2;</code>
     */
    com.google.protobuf.ByteString
        getHashPasswordBytes();
  }
  /**
   * <pre>
   * Запрос на авторизацию на сервере 
   * </pre>
   *
   * Protobuf type {@code aime.game.protobuf.protocol.MessageLoginRequest}
   */
  public  static final class MessageLoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aime.game.protobuf.protocol.MessageLoginRequest)
      MessageLoginRequestOrBuilder {
    // Use MessageLoginRequest.newBuilder() to construct.
    private MessageLoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageLoginRequest() {
      login_ = "";
      hashPassword_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MessageLoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              login_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hashPassword_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageLoginRequestProtos.internal_static_aime_game_protobuf_protocol_MessageLoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageLoginRequestProtos.internal_static_aime_game_protobuf_protocol_MessageLoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageLoginRequestProtos.MessageLoginRequest.class, MessageLoginRequestProtos.MessageLoginRequest.Builder.class);
    }

    public static final int LOGIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object login_;
    /**
     * <code>string login = 1;</code>
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        login_ = s;
        return s;
      }
    }
    /**
     * <code>string login = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASH_PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object hashPassword_;
    /**
     * <code>string hash_password = 2;</code>
     */
    public java.lang.String getHashPassword() {
      java.lang.Object ref = hashPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hashPassword_ = s;
        return s;
      }
    }
    /**
     * <code>string hash_password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHashPasswordBytes() {
      java.lang.Object ref = hashPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLoginBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, login_);
      }
      if (!getHashPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hashPassword_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLoginBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, login_);
      }
      if (!getHashPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hashPassword_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageLoginRequestProtos.MessageLoginRequest)) {
        return super.equals(obj);
      }
      MessageLoginRequestProtos.MessageLoginRequest other = (MessageLoginRequestProtos.MessageLoginRequest) obj;

      boolean result = true;
      result = result && getLogin()
          .equals(other.getLogin());
      result = result && getHashPassword()
          .equals(other.getHashPassword());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getLogin().hashCode();
      hash = (37 * hash) + HASH_PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getHashPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageLoginRequestProtos.MessageLoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageLoginRequestProtos.MessageLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageLoginRequestProtos.MessageLoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Запрос на авторизацию на сервере 
     * </pre>
     *
     * Protobuf type {@code aime.game.protobuf.protocol.MessageLoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aime.game.protobuf.protocol.MessageLoginRequest)
        MessageLoginRequestProtos.MessageLoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageLoginRequestProtos.internal_static_aime_game_protobuf_protocol_MessageLoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageLoginRequestProtos.internal_static_aime_game_protobuf_protocol_MessageLoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageLoginRequestProtos.MessageLoginRequest.class, MessageLoginRequestProtos.MessageLoginRequest.Builder.class);
      }

      // Construct using MessageLoginRequestProtos.MessageLoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        login_ = "";

        hashPassword_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageLoginRequestProtos.internal_static_aime_game_protobuf_protocol_MessageLoginRequest_descriptor;
      }

      public MessageLoginRequestProtos.MessageLoginRequest getDefaultInstanceForType() {
        return MessageLoginRequestProtos.MessageLoginRequest.getDefaultInstance();
      }

      public MessageLoginRequestProtos.MessageLoginRequest build() {
        MessageLoginRequestProtos.MessageLoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageLoginRequestProtos.MessageLoginRequest buildPartial() {
        MessageLoginRequestProtos.MessageLoginRequest result = new MessageLoginRequestProtos.MessageLoginRequest(this);
        result.login_ = login_;
        result.hashPassword_ = hashPassword_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageLoginRequestProtos.MessageLoginRequest) {
          return mergeFrom((MessageLoginRequestProtos.MessageLoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageLoginRequestProtos.MessageLoginRequest other) {
        if (other == MessageLoginRequestProtos.MessageLoginRequest.getDefaultInstance()) return this;
        if (!other.getLogin().isEmpty()) {
          login_ = other.login_;
          onChanged();
        }
        if (!other.getHashPassword().isEmpty()) {
          hashPassword_ = other.hashPassword_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageLoginRequestProtos.MessageLoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageLoginRequestProtos.MessageLoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object login_ = "";
      /**
       * <code>string login = 1;</code>
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string login = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login = 1;</code>
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string login = 1;</code>
       */
      public Builder clearLogin() {
        
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <code>string login = 1;</code>
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        login_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hashPassword_ = "";
      /**
       * <code>string hash_password = 2;</code>
       */
      public java.lang.String getHashPassword() {
        java.lang.Object ref = hashPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hashPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hash_password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHashPasswordBytes() {
        java.lang.Object ref = hashPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hashPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hash_password = 2;</code>
       */
      public Builder setHashPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hashPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hash_password = 2;</code>
       */
      public Builder clearHashPassword() {
        
        hashPassword_ = getDefaultInstance().getHashPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string hash_password = 2;</code>
       */
      public Builder setHashPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hashPassword_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:aime.game.protobuf.protocol.MessageLoginRequest)
    }

    // @@protoc_insertion_point(class_scope:aime.game.protobuf.protocol.MessageLoginRequest)
    private static final MessageLoginRequestProtos.MessageLoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageLoginRequestProtos.MessageLoginRequest();
    }

    public static MessageLoginRequestProtos.MessageLoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageLoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<MessageLoginRequest>() {
      public MessageLoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageLoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageLoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageLoginRequest> getParserForType() {
      return PARSER;
    }

    public MessageLoginRequestProtos.MessageLoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aime_game_protobuf_protocol_MessageLoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aime_game_protobuf_protocol_MessageLoginRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031MessageLoginRequest.proto\022\033aime.game.p" +
      "rotobuf.protocol\";\n\023MessageLoginRequest\022" +
      "\r\n\005login\030\001 \001(\t\022\025\n\rhash_password\030\002 \001(\tB[\n" +
      "%com.aime.game.netty.protobuf.protocolB\031" +
      "MessageLoginRequestProtos\252\002\026Aime.Protobu" +
      "f.Protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_aime_game_protobuf_protocol_MessageLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aime_game_protobuf_protocol_MessageLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aime_game_protobuf_protocol_MessageLoginRequest_descriptor,
        new java.lang.String[] { "Login", "HashPassword", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
