// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageLoginSuccessful.proto

package com.aime.game.netty.common.protobuf;

public final class MessageLoginSuccessfulProtos {
  private MessageLoginSuccessfulProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageLoginSuccessfulOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aime.game.protobuf.protocol.MessageLoginSuccessful)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string matchmaking_server = 1;</code>
     */
    java.lang.String getMatchmakingServer();
    /**
     * <code>string matchmaking_server = 1;</code>
     */
    com.google.protobuf.ByteString
        getMatchmakingServerBytes();

    /**
     * <code>int32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>string token_access = 3;</code>
     */
    java.lang.String getTokenAccess();
    /**
     * <code>string token_access = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenAccessBytes();

    /**
     * <code>int32 token_expire = 4;</code>
     */
    int getTokenExpire();
  }
  /**
   * <pre>
   **
   * Ответ на удачный запрос при авторизации
   * - первый экземпляр на matchmaking server
   * - второй экземпляр пользователю
   * </pre>
   *
   * Protobuf type {@code aime.game.protobuf.protocol.MessageLoginSuccessful}
   */
  public  static final class MessageLoginSuccessful extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aime.game.protobuf.protocol.MessageLoginSuccessful)
      MessageLoginSuccessfulOrBuilder {
    // Use MessageLoginSuccessful.newBuilder() to construct.
    private MessageLoginSuccessful(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageLoginSuccessful() {
      matchmakingServer_ = "";
      port_ = 0;
      tokenAccess_ = "";
      tokenExpire_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MessageLoginSuccessful(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              matchmakingServer_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              tokenAccess_ = s;
              break;
            }
            case 32: {

              tokenExpire_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful.class, com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful.Builder.class);
    }

    public static final int MATCHMAKING_SERVER_FIELD_NUMBER = 1;
    private volatile java.lang.Object matchmakingServer_;
    /**
     * <code>string matchmaking_server = 1;</code>
     */
    public java.lang.String getMatchmakingServer() {
      java.lang.Object ref = matchmakingServer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matchmakingServer_ = s;
        return s;
      }
    }
    /**
     * <code>string matchmaking_server = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMatchmakingServerBytes() {
      java.lang.Object ref = matchmakingServer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matchmakingServer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int TOKEN_ACCESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object tokenAccess_;
    /**
     * <code>string token_access = 3;</code>
     */
    public java.lang.String getTokenAccess() {
      java.lang.Object ref = tokenAccess_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenAccess_ = s;
        return s;
      }
    }
    /**
     * <code>string token_access = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenAccessBytes() {
      java.lang.Object ref = tokenAccess_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenAccess_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_EXPIRE_FIELD_NUMBER = 4;
    private int tokenExpire_;
    /**
     * <code>int32 token_expire = 4;</code>
     */
    public int getTokenExpire() {
      return tokenExpire_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMatchmakingServerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, matchmakingServer_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (!getTokenAccessBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tokenAccess_);
      }
      if (tokenExpire_ != 0) {
        output.writeInt32(4, tokenExpire_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMatchmakingServerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, matchmakingServer_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (!getTokenAccessBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tokenAccess_);
      }
      if (tokenExpire_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, tokenExpire_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful)) {
        return super.equals(obj);
      }
      com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful other = (com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful) obj;

      boolean result = true;
      result = result && getMatchmakingServer()
          .equals(other.getMatchmakingServer());
      result = result && (getPort()
          == other.getPort());
      result = result && getTokenAccess()
          .equals(other.getTokenAccess());
      result = result && (getTokenExpire()
          == other.getTokenExpire());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MATCHMAKING_SERVER_FIELD_NUMBER;
      hash = (53 * hash) + getMatchmakingServer().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + TOKEN_ACCESS_FIELD_NUMBER;
      hash = (53 * hash) + getTokenAccess().hashCode();
      hash = (37 * hash) + TOKEN_EXPIRE_FIELD_NUMBER;
      hash = (53 * hash) + getTokenExpire();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Ответ на удачный запрос при авторизации
     * - первый экземпляр на matchmaking server
     * - второй экземпляр пользователю
     * </pre>
     *
     * Protobuf type {@code aime.game.protobuf.protocol.MessageLoginSuccessful}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aime.game.protobuf.protocol.MessageLoginSuccessful)
        com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessfulOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful.class, com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful.Builder.class);
      }

      // Construct using com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        matchmakingServer_ = "";

        port_ = 0;

        tokenAccess_ = "";

        tokenExpire_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_descriptor;
      }

      public com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful getDefaultInstanceForType() {
        return com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful.getDefaultInstance();
      }

      public com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful build() {
        com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful buildPartial() {
        com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful result = new com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful(this);
        result.matchmakingServer_ = matchmakingServer_;
        result.port_ = port_;
        result.tokenAccess_ = tokenAccess_;
        result.tokenExpire_ = tokenExpire_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful) {
          return mergeFrom((com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful other) {
        if (other == com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful.getDefaultInstance()) return this;
        if (!other.getMatchmakingServer().isEmpty()) {
          matchmakingServer_ = other.matchmakingServer_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (!other.getTokenAccess().isEmpty()) {
          tokenAccess_ = other.tokenAccess_;
          onChanged();
        }
        if (other.getTokenExpire() != 0) {
          setTokenExpire(other.getTokenExpire());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object matchmakingServer_ = "";
      /**
       * <code>string matchmaking_server = 1;</code>
       */
      public java.lang.String getMatchmakingServer() {
        java.lang.Object ref = matchmakingServer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matchmakingServer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matchmaking_server = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMatchmakingServerBytes() {
        java.lang.Object ref = matchmakingServer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matchmakingServer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matchmaking_server = 1;</code>
       */
      public Builder setMatchmakingServer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matchmakingServer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matchmaking_server = 1;</code>
       */
      public Builder clearMatchmakingServer() {
        
        matchmakingServer_ = getDefaultInstance().getMatchmakingServer();
        onChanged();
        return this;
      }
      /**
       * <code>string matchmaking_server = 1;</code>
       */
      public Builder setMatchmakingServerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matchmakingServer_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object tokenAccess_ = "";
      /**
       * <code>string token_access = 3;</code>
       */
      public java.lang.String getTokenAccess() {
        java.lang.Object ref = tokenAccess_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tokenAccess_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token_access = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenAccessBytes() {
        java.lang.Object ref = tokenAccess_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenAccess_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token_access = 3;</code>
       */
      public Builder setTokenAccess(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tokenAccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token_access = 3;</code>
       */
      public Builder clearTokenAccess() {
        
        tokenAccess_ = getDefaultInstance().getTokenAccess();
        onChanged();
        return this;
      }
      /**
       * <code>string token_access = 3;</code>
       */
      public Builder setTokenAccessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tokenAccess_ = value;
        onChanged();
        return this;
      }

      private int tokenExpire_ ;
      /**
       * <code>int32 token_expire = 4;</code>
       */
      public int getTokenExpire() {
        return tokenExpire_;
      }
      /**
       * <code>int32 token_expire = 4;</code>
       */
      public Builder setTokenExpire(int value) {
        
        tokenExpire_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 token_expire = 4;</code>
       */
      public Builder clearTokenExpire() {
        
        tokenExpire_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:aime.game.protobuf.protocol.MessageLoginSuccessful)
    }

    // @@protoc_insertion_point(class_scope:aime.game.protobuf.protocol.MessageLoginSuccessful)
    private static final com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful();
    }

    public static com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageLoginSuccessful>
        PARSER = new com.google.protobuf.AbstractParser<MessageLoginSuccessful>() {
      public MessageLoginSuccessful parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageLoginSuccessful(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageLoginSuccessful> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageLoginSuccessful> getParserForType() {
      return PARSER;
    }

    public com.aime.game.netty.common.protobuf.MessageLoginSuccessfulProtos.MessageLoginSuccessful getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034MessageLoginSuccessful.proto\022\033aime.gam" +
      "e.protobuf.protocol\"n\n\026MessageLoginSucce" +
      "ssful\022\032\n\022matchmaking_server\030\001 \001(\t\022\014\n\004por" +
      "t\030\002 \001(\005\022\024\n\014token_access\030\003 \001(\t\022\024\n\014token_e" +
      "xpire\030\004 \001(\005B\\\n#com.aime.game.netty.commo" +
      "n.protobufB\034MessageLoginSuccessfulProtos" +
      "\252\002\026Aime.Protobuf.Protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aime_game_protobuf_protocol_MessageLoginSuccessful_descriptor,
        new java.lang.String[] { "MatchmakingServer", "Port", "TokenAccess", "TokenExpire", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
